// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_zBaOPgPvrFCu1vIOCMbmDokFxMOpecM',
    appId: '1:25727079810:android:9d3403a63fc77ed3a16b9b',
    messagingSenderId: '25727079810',
    projectId: 'social-media-flutter-f1a31',
    databaseURL: 'https://social-media-flutter-f1a31-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-flutter-f1a31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpZwHFR-t2EjnifI0md3P5v6NSaifSYpU',
    appId: '1:25727079810:ios:93fa263e9b9f80cda16b9b',
    messagingSenderId: '25727079810',
    projectId: 'social-media-flutter-f1a31',
    databaseURL: 'https://social-media-flutter-f1a31-default-rtdb.firebaseio.com',
    storageBucket: 'social-media-flutter-f1a31.appspot.com',
    iosBundleId: 'com.esprit.WeBuild.socialMediaApplication',
  );
}
