name: social_media_application
description: "social media replica"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2  # Add the image_picker dependency
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
  custom_like_button: ^0.0.5
  intl: ^0.20.1
  cloud_firestore: ^5.0.0

  curved_navigation_bar: ^1.0.3
  story_view: ^0.16.5
  share_plus: ^10.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

